# Railway configuration for optimized Docker builds
# Using Docker with multi-stage build for 60% smaller image (535MB vs 1.34GB)

[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend/Dockerfile"

# Watch only backend-related files for rebuilds
watchPatterns = [
  "apps/backend/**",
  "libs/backend/**",
  "libs/shared/**",
  "package.json",
  "pnpm-lock.yaml"
]

[deploy]
# Start command handled by Dockerfile CMD (omitted to use Dockerfile default)

# Health check configuration
healthcheckPath = "/api/v1/healthz"
healthcheckTimeout = 30

# Restart policy for production stability
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Zero-downtime deployment settings
overlapSeconds = 60
drainingSeconds = 30

# Multi-region configuration for production
[deploy.multiRegionConfig."europe-west4-drams3a"]
numReplicas = 1

# Environment-specific overrides
[environments.production.deploy]
# Scale up for production if needed
multiRegionConfig = { "europe-west4-drams3a" = { numReplicas = 2 } }

[environments.staging.deploy]
# Single replica for staging
multiRegionConfig = { "europe-west4-drams3a" = { numReplicas = 1 } }

# PR environment configuration
[environments.pr.deploy]
# Minimal resources for PR previews
multiRegionConfig = { "europe-west4-drams3a" = { numReplicas = 1 } }
healthcheckTimeout = 60