[build]
builder = "DOCKERFILE"
watchPatterns = ["apps/worker/**","libs/backend/**","libs/shared/**","package.json","pnpm-lock.yaml"]
dockerfilePath = "apps/worker/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
overlapSeconds = 60
drainingSeconds = 30
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5