version: '3.8'

services:
  chaos-runner:
    build:
      context: ../..
      dockerfile: docker/chaos-runner/Dockerfile
    environment:
      - CHAOS_SCRIPTS_DIR=/chaos-engineering/scripts
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined  # Required for chaos testing
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
      - /chaos-engineering/logs:noexec,nosuid,size=50m
      - /chaos-engineering/reports:noexec,nosuid,size=50m
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN  # Required for network chaos experiments
    networks:
      - chaos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import chaostoolkit; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
      nproc:
        soft: 32
        hard: 64
    mem_limit: 512m
    cpus: 0.5

networks:
  chaos-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"