name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: echo "Test workflow is working"